[package]
name = "nixpkgs-track"
version = "0.1.0"
authors = ["uncenter <uncenter@uncenter.dev>"]
license = "MIT"
description = "Track where Nixpkgs pull requests have reached."
readme = "README.md"
homepage = "https://github.com/uncenter/nixpkgs-track"
repository = "https://github.com/uncenter/nixpkgs-track"
keywords = ["cli"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.9", features = ["derive", "env"] }
color-eyre = "0.6.3"
etcetera = "0.8.0"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
tabled = { version = "0.15.0", features = ["ansi"] }
yansi = { version = "1.0.1", features = ["hyperlink"] }

[lints.clippy]
all = "warn"
pedantic = "warn"
